inoremap jk <ESC>
let mapleader = ","

filetype plugin indent on
syntax on
set encoding=utf-8

"Let buffers lie in the background, windowless.
set hidden

"Show me line numbers.
set number

" Highlight searches
set hlsearch

"Map Ctrl-L (redraw screen) to also turn off search highlighting until the
"next search.
nnoremap <C-L> :nohl<CR><C-L>

"Turn on our package manager thing.
execute pathogen#infect()

set background=dark
colorscheme abbott

"Tabs for indent, spaces for alignment.
set noexpandtab
set softtabstop=0
set shiftwidth=4
set tabstop=4
set cindent
set cinoptions=(0,u0,U0

let g:ctrlp_working_path_mode='ra'
